ALTER SEQUENCE category_id_seq RESTART WITH 1;
ALTER SEQUENCE comentary_id_seq RESTART WITH 1;
ALTER SEQUENCE queixinha_id_seq RESTART WITH 1;
ALTER SEQUENCE queixinha_user_id_seq RESTART WITH 1;
ALTER SEQUENCE user_id_seq RESTART WITH 1;
ALTER SEQUENCE vote_id_seq RESTART WITH 1;